server.host: "0"
server.name: kibana
server.ssl.enabled: true
server.ssl.key: /usr/share/kibana/config/kibana.key
server.ssl.certificate: /usr/share/kibana/config/kibana.crt

elasticsearch.username: "kibana"
elasticsearch.password: "kibanapassword"
elasticsearch.url: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

xpack.security.enabled: false
xpack.security.sessionTimeout: 600000

xpack.monitoring.ui.container.elasticsearch.enabled: true
#xpack.security.encryptionKey: "something_at_least_32_characters"