<<<<<<< HEAD:meu/kibana/config/kibana.yml
---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.url: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
=======
server.host: "0"
server.name: kibana
server.ssl.enabled: true
server.ssl.key: /usr/share/kibana/config/kibana.key
server.ssl.certificate: /usr/share/kibana/config/kibana.crt

elasticsearch.username: "kibana"
elasticsearch.password: "kibanapassword"
elasticsearch.url: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

xpack.security.enabled: false
xpack.security.sessionTimeout: 600000

xpack.monitoring.ui.container.elasticsearch.enabled: true
#xpack.security.encryptionKey: "something_at_least_32_characters"
>>>>>>> 769fe857836167ed691f38329594b110db96cc1f:kibana/config/kibana.yml
