version: '3'

networks:
  stack_elk:
    driver: bridge

services:

  elasticsearch:
    build:
      context: elasticsearch/
    privileged: true
    hostname: elasticsearch
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      CLUSTER_NAME: "elasticsearch-cluster"
      NODE_MASTER: "true"
      NODE_DATA: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - stack_elk

  kibana:
    build:
      context: kibana/
    privileged: true
    hostname: kibana
    container_name: kibana
    restart: unless-stopped
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOST: "elasticsearch"
      ELASTICSEARCH_PORT: "9200"
    ports:
      - "5601:5601"
    networks:
      - stack_elk
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
    privileged: true
    hostname: logstash
    container_name: logstash
    restart: unless-stopped
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - ./logstash/patterns/default.conf:/opt/logstash/patterns/default.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTICSEARCH_HOST: "elasticsearch"
      ELASTICSEARCH_PORT: "9200"
    networks:
      - stack_elk
    depends_on:
      - elasticsearch