####################################################################################################
version: '3.6'
#
# Rede
#
networks:
  elk:
    driver: bridge

# Serviços ELK
#
services:
#
# O Elasticsearch é o servidor de busca distribuido que irá armazenar os logs.
#
  elasticsearch:
    build:
      context: elasticsearch/
    privileged: true
    hostname: elasticsearch
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      CLUSTER_NAME: "elasticsearch-cluster"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk
#
# O Kibana permite a criação de vizualizações e dashboards baseadas em buscas realizadas no elasticsearch.
#
  kibana:
    build:
      context: kibana/
    privileged: true
    hostname: kibana
    container_name: kibana
    restart: unless-stopped
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOST: "elasticsearch"
      ELASTICSEARCH_PORT: "9200"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
#
# O Logstash é o responsável por parsear os logs e enviar para o elasticsearch.
#
  logstash:
    build:
      context: logstash/
    privileged: true
    hostname: logstash
    container_name: logstash
    restart: unless-stopped
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - ./logstash/patterns/default.conf:/opt/logstash/patterns/default.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_HOST: "elasticsearch"
      ELASTICSEARCH_PORT: "9200"
    networks:
      - elk
    depends_on:
      - elasticsearch
#
# O Filebeat é responsável por ler os arquivos de log e enviar para o logstash.
#
  filebeat:
    build:
      context: filebeat/
    privileged: true
    hostname: filebeat
    container_name: filebeat
    restart: unless-stopped
    volumes:
      - ./filebeat/config/filebeat.yml:/filebeat.yml
    environment:
      LOGSTASH_HOST: "logstash"
      LOGSTASH_PORT: "5044"
    networks:
      - elk
    depends_on:
      - logstash
#
# O Metricbeat é responsável por usa as métricas e estatísticas que coleta e envia para a saída especificada, como Elasticsearch ou Logstash
#
  metricbeat:
    build:
      context: metricbeat/
    privileged: true
    hostname: metricbeat
    container_name: metricbeat
    restart: unless-stopped
    volumes:
      - ./metricbeat/config/metricbeat.yml:/etc/metricbeat/metricbeat.yml
    environment:
      LOGSTASH_HOST: "logstash"
      LOGSTASH_PORT: "5044"
      KIBANA_HOST: "kibana"
      KIBANA_PORT: "5601"
    networks:
      - elk
    depends_on:
      - logstash
####################################################################################################