- module: docker
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  
  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true