# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1

LABEL urL-elasticsearch-home="http://localhost:9200/" \
	urL-elasticsearch-contexts="http://localhost:9200/_cat" \
	urL-elasticsearch-mapping="http://localhost:9200/_mapping"

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
