version: '3'
networks:
  stack_elk:
    driver: bridge
services:
#
# O Elasticsearch é o servidor de busca distribuido que irá armazenar os logs.
#
  elasticsearch_node_master:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - stack_elk
    volumes:
      - elasticsearch_data_local_1:/usr/share/elasticsearch/data
      - ./elasticsearch/create-certs/certs:$CERTS_DIR_ELASTICSEARCH
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      CLUSTER_NAME: "elasticsearch_cluster"
      NODE_MASTER: "true"
      NODE_DATA: "true"
      NETWORK_HOST: "0.0.0.0"
      DISCOVERY_ZEN_MINIMUM_MASTER_NODES: "1"
      DISCOVERY_ZEN_PING_TIMEOUT: "10s"
      DISCOVERY_ZEN_PING_UNICAST_HOSTS: "elasticsearch"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - MAX_LOCKED_MEMORY=unlimited
      - cluster.name=elasticsearch_cluster
      - node.name=elasticsearch_node_master
      - node.master=true
      - node.data=true
      - network.host=0.0.0.0
      - discovery.zen.ping_timeout=30s
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.ping.unicast.hosts=elasticsearch_node_master
      - xpack.license.self_generated.type=trial 
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.http.ssl.key=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_master/elasticsearch_node_master.key
      - xpack.security.http.ssl.certificate=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_master/elasticsearch_node_master.crt
      - xpack.ssl.certificate_authorities=$CERTS_DIR_ELASTICSEARCH/ca/ca.crt
      - xpack.ssl.certificate=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_master/elasticsearch_node_master.crt
      - xpack.ssl.key=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_master/elasticsearch_node_master.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl --cacert $CERTS_DIR_ELASTICSEARCH/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch_node_worker:
    container_name: elasticsearch_node_worker
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    hostname: elasticsearch_node_worker
    ports:
      - "9200"
      - "9300"
    networks:
      - stack_elk
    volumes:
      - elasticsearch_data_local_2:/usr/share/elasticsearch/data
      - ./elasticsearch/create-certs/certs:$CERTS_DIR_ELASTICSEARCH
    environment:
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - MAX_LOCKED_MEMORY=unlimited
      - cluster.name=elasticsearch_cluster
      - node.name=elasticsearch_node_worker
      - node.master=false
      - node.data=true
      - network.host=0.0.0.0
      - discovery.zen.ping_timeout=30s
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.ping.unicast.hosts=elasticsearch_node_master
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.http.ssl.key=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_worker/elasticsearch_node_worker.key
      - xpack.security.http.ssl.certificate=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_worker/elasticsearch_node_worker.crt
      - xpack.ssl.certificate_authorities=$CERTS_DIR_ELASTICSEARCH/ca/ca.crt
      - xpack.ssl.certificate=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_worker/elasticsearch_node_worker.crt
      - xpack.ssl.key=$CERTS_DIR_ELASTICSEARCH/elasticsearch_node_worker/elasticsearch_node_worker.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
#
# O Kibana permite a criação de vizualizações e dashboards baseadas em buscas realizadas no elasticsearch.
#
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${TAG}
    hostname: kibana
    ports:
      - "5601:5601"
    networks:
      - stack_elk
    depends_on:
      - elasticsearch_node_master
#
# O Logstash é o responsável por parsear os logs e enviar para o elasticsearch.
#
  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    hostname: logstash
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - stack_elk
    volumes:
      - ./logstash/patterns/default.conf:/opt/logstash/patterns/default.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTICSEARCH_PORT: "9200"
      ELASTICSEARCH_HOST: "elasticsearch_node_master"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s      
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    depends_on:
      - elasticsearch_node_master
