#-------------------------- Metricbeat Modules -------------------------------#
metricbeat.modules:
#------------------------------- System Module -------------------------------#
- module: system
  metricsets:
    - cpu             # CPU usage
    - filesystem      # File system usage for each mountpoint
    - fsstat          # File system summary metrics
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - core           # Per CPU core usage
    - diskio         # Disk IO
    - raid           # Raid
    - socket         # Sockets and connection info (linux only)
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]
#------------------------------- Docker Module -------------------------------#
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true
#------------------------------ Logstash Output ------------------------------#
output.logstash:
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
#------------------------------- Setup Kibana --------------------------------#
setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"