#-------------------------- Metricbeat Modules -------------------------------#
metricbeat.modules:
- module: system
  metricsets:
    - cpu             # CPU usage
    - filesystem      # File system usage for each mountpoint
    - fsstat          # File system summary metrics
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - core           # Per CPU core usage
    - diskio         # Disk IO
    #- raid           # Raid
    - socket         # Sockets and connection info (linux only)
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false
#----------------------------- Logstash output --------------------------------#
output.logstash:
  enabled: true
  hosts: ["{{LOGSTASH_HOST}}:{{LOGSTASH_PORT}}"]
  index: "metricbeat-%{yyyy.MM.dd}"
#----------------------------- Setup Kibana -----------------------------------#
setup.kibana:
  host: "{{KIBANA_HOST}}:{{KIBANA_PORT}}"