---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.host: "0"
server.name: kibana
elasticsearch.url: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
